### ISSUE TITLE
Compatibility with Neos 3.0

### ISSUE THREAD

**Issue by jonnitto** [PackageFactory/PackageFactory.OffRoad#6]

**Comment by iseries** [comment]
Hey Jon,
is this package still in active development?

**Comment by jonnitto** [comment]
I don't know. @mficzel or @grebaldi should know it ;-)

**Comment by mficzel** [comment]
@iseries @jonnitto ... did not remember this package any more so this says al lot already. 

No this is not maintained any more. We recommend https://github.com/Flowpack/neos-dimensionresolver if you are dealing with dimensions.

**Comment by mficzel** [comment]
I added a deprecation notice and will archive this repo now.
